### ISSUE TITLE
Feature freeze and code review 11/01/11

### ISSUE THREAD

**Issue by MattWindsor91** [MattWindsor91/crystals#14]
It's time, in my humble opinion, for the first ever crystals feature freeze!

In a bid to ensure all code contributed to crystals so far is of optimal quality (both written and compiled), normal progress on crystals is going to halt in order to allow for the work currently in staging to be properly reviewed and prepared for master.

The code review will take four forms:
- Intensive valgrind testing, to ensure that there are no noticeable memory leaks or errors.
- Refactoring of code to increase consistency/coherency and decrease coupling.
- Consistency-checking of code style to ensure everything follows crystals's standards (some style guides may need writing up).
- Improvement to documentation so that new coders can more easily jump in.

No more feature pulls will be allowed into staging between now and the closure of this issue. The final push to master in this space will likely be tagged as version 0.01.

Hopefully, there will be a more detailed action plan going up soon.

Thanks to everyone who has worked on crystals so far! Even though crystals isn't capable of much yet, it's a start and I think the amount of work that has gone into it despite university and other more important issues is something to be proud of.

~ Matt

PS: Java map editor will be going up shortly.

**Comment by giselher** [comment]
We should create dummy modules and bindings to test for memory leaks in our own code. Most of the leaks are becaues of third-party librarys.

I will upload src/bindings/dummy.c if you agree.

**Comment by giselher** [comment]
dummy.c uploaded!

I also rewrote parser.c. It doesn't add any new functions, it just allocates less memory and is more stable (not enough test, but should be).
https://github.com/CaptainHayashi/crystals/blob/77f7e8483db3b52e343d22a46aea25ff1c87f1a0/src/parser.c

**Comment by MattWindsor91** [comment]
Given that this pretty early feature freeze has become a pretty lengthy complete project freeze, I'm going to pretty much abandon this and open staging again.

I'm not sure what to do with crystals, but I don't particularly want to see it completely die.  There should probably be some discussion on how to work on it, as I may have caused a few wounds with my silly management decisions, and I definitely feel the bureaucracy creep may have been a bad step.

I'll be in freenode #crystals or around this github =P.
