### ISSUE TITLE
The end of bureaucracy (and there was much rejoicing)

### ISSUE THREAD

**Issue by MattWindsor91** [MattWindsor91/crystals#26]
Pursuant to something barrucadu raised in person, and given that there is such a lack of development interest in the project, I've decided to drop the formal procedure for merging changes.

As of now,
- Staging is deprecated.  Its role as a collection of (relatively) stable things people have been working on goes to master, which will immediately be pushed to with the contents of staging as they are at the moment.
- Anyone with access to this repository may pull their work into master when they feel it's stable enough.  No need for a pull request.
- Pull requests into this repository no longer need a majority vote, and anyone can merge them.
- Anyone breaking the codebase (by pulling broken code into master, etc) is liable to get moaned at by the other developers, but that's up to said developers.  **It's no longer an issue of policy to keep master tidy, but out of courtesy to others (developers and users- pah, users!- alike) you should definitely make an effort to do so.**
- Issues that affect the project will still be posted up here for discussion, but at the end of the day it's up to developers to reach equilibrium about the consequences.
- **No.  More.  Feature.  Freezes.**

Apologies to giselher, who I'm aware gets left out of a lot of discussion about the project because of majority consensus being achieved by myself and barrucadu all the time.

**Comment by giselher** [comment]
I am OK with this.

Sorry for the late response, but I was moving to Hagenberg.

**Comment by giselher** [comment]
As this is coming into effect (?) I will close this Issue, but I like to put some of the items somewhere on the project wiki.
